import { CaretPluginSettings } from "../types";

export const DEFAULT_SETTINGS: CaretPluginSettings = {
    caret_version: "0.2.80",
    chat_logs_folder: "caret/chats",
    chat_logs_date_format_bool: false,
    chat_logs_rename_bool: true,
    chat_send_chat_shortcut: "enter",
    model: "gpt-4-turbo",
    llm_provider: "openai",
    openai_api_key: "",
    groq_api_key: "",

    anthropic_api_key: "",
    open_router_key: "",
    xai_api_key: "",
    context_window: 128000,
    custom_endpoints: {},
    system_prompt: "",
    temperature: 1,
    llm_provider_options: {
        openai: {
            "gpt-4-turbo": {
                name: "gpt-4-turbo",
                context_window: 128000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gpt-4o": {
                name: "gpt-4o",
                context_window: 128000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gpt-4o-mini": {
                name: "gpt-4o-mini",
                context_window: 128000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "chatgpt-4o-latest": {
                name: "ChatGPT-4O Latest",
                context_window: 128000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "o1-preview": {
                name: "o1-preview",
                context_window: 128000,
                function_calling: false,
                vision: false,
                streaming: false,
            },
            "o1-mini": {
                name: "o1-mini",
                context_window: 128000,
                function_calling: false,
                vision: false,
                streaming: false,
            },
            o1: {
                name: "o1",
                context_window: 200000,
                function_calling: false,
                vision: false,
                streaming: false,
            },
            "o3-mini": {
                name: "o3-mini",
                context_window: 200000,
                function_calling: false,
                vision: false,
                streaming: false,
            },
            o3: {
                name: "o3",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "o4-mini": {
                name: "o4-mini",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gpt-5": {
                name: "GPT-5",
                context_window: 400000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gpt-5-mini": {
                name: "GPT-5 Mini",
                context_window: 400000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gpt-5-nano": {
                name: "GPT-5 Nano",
                context_window: 400000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gpt-5-chat-latest": {
                name: "GPT-5 Chat Latest",
                context_window: 400000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
        },
        groq: {
            "llama3-8b-8192": {
                name: "Llama 8B",
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            "llama3-70b-8192": {
                name: "Llama 70B",
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            "mixtral-8x7b-32768": {
                name: "Mixtral 8x7b",
                context_window: 32768,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            "gemma-7b-it": {
                name: "Gemma 7B",
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            // In preview, not accessiable yet
            "llama-3.1-8b-instant": {
                name: "llama 3.1 8B Instant (Preview)",
                context_window: 8000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "llama-3.1-70b-versatile": {
                name: "llama 3.1 70B Versatile (Preview)",
                context_window: 8000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
        },
        anthropic: {
            "claude-sonnet-4-5": {
                name: "Claude Sonnet 4.5",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "claude-haiku-4-5": {
                name: "Claude Haiku 4.5",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "claude-opus-4-1": {
                name: "Claude Opus 4.1",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "claude-opus-4-0": {
                name: "Claude Opus 4.0",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "claude-sonnet-4-0": {
                name: "Claude Sonnet 4.0",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "claude-3-5-sonnet-20240620": {
                name: "Claude 3.5 Sonnet",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "claude-3-opus-20240229": {
                name: "Claude 3 Opus",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "claude-3-sonnet-20240229": {
                name: "Claude 3 Sonnet",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },

            "claude-3-haiku-20240307": {
                name: "Claude 3 Haiku",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
        },
        openrouter: {
            "anthropic/claude-3-opus": {
                name: "Claude 3 Opus",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "anthropic/claude-3-sonnet": {
                name: "Claude 3 Sonnet",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "anthropic/claude-3.5-sonnet": {
                name: "Claude 3.5 Sonnet",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "anthropic/claude-3-haiku": {
                name: "Claude 3 Haiku",
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "google/gemini-flash-1.5": {
                name: "Gemini Flash 1.5",
                context_window: 2800000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "google/gemini-pro-1.5": {
                name: "Gemini Pro 1.5",
                context_window: 2800000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "google/gemini-flash-1.5-exp": {
                name: "Gemini Flash 1.5 Experimental",
                context_window: 4000000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "meta-llama/llama-3.1-405b-instruct": {
                name: "Llama3.1 405B Instruct",
                context_window: 131072,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "meta-llama/llama-3.1-8b-instruct": {
                name: "Llama3.1 8B Instruct",
                context_window: 100000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "meta-llama/llama-3.1-70b-instruct": {
                name: "Llama3.1 70B Instruct",
                context_window: 100000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
        },
        ollama: {
            "llama3.1": {
                name: "llama3.1 8B",
                context_window: 131072,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            llama3: {
                name: "llama3 8B",
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            "llama3.2:1b": {
                name: "llama3.2 1B",
                context_window: 131072,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            "llama3.2:3b": {
                name: "llama3.2 3B",
                context_window: 131072,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            phi3: {
                name: "Phi-3 3.8B",
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            mistral: {
                name: "Mistral 7B",
                context_window: 32768,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            gemma: {
                name: "Gemma 7B",
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            gemma2: {
                name: "Gemma 2",
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            "deepseek-r1:1.5b": {
                name: "DeepSeek r1 1.5B",
                context_window: 131072,
                function_calling: false,
                vision: false,
                streaming: true,
            },

            "deepseek-r1:8b": {
                name: "DeepSeek r1 8B",
                context_window: 131072,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            "deepseek-r1:14b": {
                name: "DeepSeek r1 14B",
                context_window: 131072,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            "deepseek-r1:32b": {
                name: "DeepSeek r1 32B",
                context_window: 131072,
                function_calling: false,
                vision: false,
                streaming: true,
            },
        },
        custom: {},
        google: {
            "gemini-2.5-pro": {
                name: "Gemini 2.5 Pro",
                context_window: 1048576,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gemini-2.5-flash": {
                name: "Gemini 2.5 Flash",
                context_window: 1048576,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gemini-2.5-flash-lite": {
                name: "Gemini 2.5 Flash Lite",
                context_window: 1048576,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gemini-2.0-flash": {
                name: "Gemini 2.0 Flash",
                context_window: 1048576,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gemini-2.0-flash-lite-preview-02-05": {
                name: "Gemini 2.0 Flash Lite Preview",
                context_window: 1048576,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gemini-2.0-pro-exp-02-05": {
                name: "Gemini 2.0 Pro Exp (Rate Limited)",
                context_window: 1048576,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gemini-1.5-pro": {
                name: "Gemini 1.5 Pro",
                context_window: 800000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            "gemini-1.5-flash": {
                name: "Gemini 1.5 Flash",
                context_window: 400000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
        },
        deepseek:{
            "deepseek-chat":{
                name: "DeepSeek Chat",
                context_window: 128000,
                function_calling: true,
                vision: true,
                streaming: true,
            }
        },
        perplexity: {
            "llama-3.1-sonar-small-128k-online": {
                name: "Sonar Small",
                context_window: 127072,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            "llama-3.1-sonar-large-128k-online": {
                name: "Sonar Large",
                context_window: 127072,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            "llama-3.1-sonar-huge-128k-online": {
                name: "Sonar Huge",
                context_window: 127072,
                function_calling: false,
                vision: false,
                streaming: true,
            },
        },
    },
    provider_dropdown_options: {
        openai: "OpenAI",
        groq: "Groq",
        ollama: "Ollama",
        anthropic: "Anthropic",
        openrouter: "OpenRouter",
        custom: "Custom",
        google: "Google Gemini",
        perplexity: "Perplexity",
        deepseek: "DeepSeek",
    },
    include_nested_block_refs: true,
    google_api_key: "",
    perplexity_api_key: "",
    image_model: "dall-e-3",
    image_provider: "openai",
    image_model_options: {
        openai: {
            "gpt-image-1": {
                name: "GPT Image 1",
                supported_sizes: ["1024x1024", "1536x1024", "1024x1536"],
            },
            "dall-e-3": {
                name: "DALL-E 3",
                supported_sizes: ["1024x1024", "1792x1024", "1024x1792"],
            },
        },
        xai: {
            "grok-2-image": {
                name: "Grok 2 Image",
                supported_sizes: ["1024x768"],
            },
        },
    },
    image_provider_dropdown_options: {
        openai: "OpenAI",
        xai: "xAI Grok",
    },
};
